import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { cookieToInitialState } from "wagmi";
import { config as wagmiConfig } from "@/lib/wagmi/config";
import { BaseLayout } from "@/components/layouts";
import { headers } from "next/headers";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(
    wagmiConfig,
    (await headers()).get("cookie")
  );

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers initialState={initialState}>
          <ToastContainer theme="dark" />
          <div id="app">
            <BaseLayout>{children}</BaseLayout>
          </div>

          <div id="modals"></div>
        </Providers>
      </body>
    </html>
  );
}
